services:
  Ed-mongo:
    image: mongo
    ports:
      - 27017:27017 #the second number is MongoDB internal port

  Ed-mongo-express:
    image: mongo-express
    ports:
      - 8081:8081 #the second number is MongoDB internal port
