services:
  Ed-mongo:
    image: mongo
    ports:
      - 27017:27017

  Ed-mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=Ed-mongo
    depends_on:
      - Ed-mongo
